version: '3'
services:
  app:
    build: ./
    container_name: app
    volumes:
      - ./:/var/www/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=dev
      - PORT=3000
      - REDIS_URL=redis://cache
    links:
      - redis

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
