version: '3'
services:
  app:
    build: ./
    volumes:
      - ./:/var/www/app
      - /var/www/app/node_modules
    ports:
      - 3000
    environment:
      - NODE_ENV=container
    links:
      - redis
  lb:
    image: dockercloud/haproxy
    links:
     - app
    ports:
     - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis
    expose:
      - 6379
