version: '3'
services:
  app:
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=container
    links:
      - redis

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
