version: '3'
services:
  app:
    build: ./
    container_name: pyapp
    volumes:
      - ./:/var/www/app
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=redis://pycache
      - REDIS_PORT=6379
    links:
      - redis

  redis:
    image: redis
    container_name: pycache
    expose:
      - 6379
